/* SPDX-License-Identifier: GPL-2.0+ OR BSD-3-Clause
 *
 * Copyright (C) 2015-2018, STMicroelectronics - All Rights Reserved
 *
 */

/*
 * File generated by STMicroelectronics STM32CubeMX DDR Tool for MPUs
 * DDR type: DDR3 / DDR3L
 * DDR width: 16bits
 * DDR density: 2Gb
 * System frequency: 533000Khz
 * Relaxed Timing Mode: false
 * Address mapping type: RBC
 *
 * Save Date: 2019.08.16, save Time: 17:02:41
 */

#define DDR_MEM_NAME	"DDR3L-1066/777 bin F 1x2Gb 533MHz"
#define DDR_MEM_SIZE	0x10000000
#define DDR_ADDRMAP6	0x0F0F0606

#include "stm32mp15-mx.h"
