#!/bin/sh
# -*- mode: shell-script; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
#
# Copyright (C) 2012, 2013, 2016 O.S. Systems Software LTDA.
# Authored-by:  Otavio Salvador <otavio@ossystems.com.br>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Add options for the script
# Copyright (C) 2013 Freescale Semiconductor, Inc.
CWD=`cd .;pwd`
PROGNAME=setup-environment
export BSPDIR="$CWD"
TEMPLATECONF=${PWD}/layers/meta-karo/base/conf

if [ -z "$BASH_VERSION" ];then
    echo "This script must to be run from bash" >&2
    return 1
fi

usage()
{
    echo -e "
Usage: MACHINE=<machine> DISTRO=<distro> source $PROGNAME <build-dir>
Usage:                                   source $PROGNAME <build-dir>
    <machine>    machine name
    <distro>     distro name
    <build-dir>  build directory

The first usage is for creating a new build directory. In this case, the
script creates the build directory <build-dir>, configures it for the
specified <machine> and <distro>, and prepares the calling shell for running
bitbake on the build directory.

The second usage is for using an existing build directory. In this case,
the script prepares the calling shell for running bitbake on the build
directory <build-dir>. The build directory configuration is unchanged.
"

    shopt -q nullglob && nullglob=false || nullglob=true
    $nullglob && shopt -s nullglob
    for s in layers/*/conf/machine/*.conf;do
        echo -e "
Supported machines: `echo; ls layers/*/conf/machine/*.conf | \
sed 's:^.*/:\t:;s/\.conf//' | sort`

Supported distros: `echo; ls layers/*/conf/distro/*.conf | \
sed 's:^.*/:\t:;s/\.conf//' | sort`

To build for a machine listed above, run this script as:
DISTRO=<distro> MACHINE=<machine> source $PROGNAME <build-dir>
"
        $nullglob && shopt -u nullglob
        return
    done
    cat << EOF
No machine configuration files found!
Make sure, to set up your yocto source directory with:
    repo init -u git@github.com:karo-electronics/karo-manifest -b master
    repo sync
EOF
    $nullglob && shopt -u nullglob
    return 1
}

clean_up()
{
   unset LIST_MACHINES VALID_MACHINE
   unset CWD TEMPLATES SHORTOPTS LONGOPTS ARGS PROGNAME
   unset generated_config updated
   unset MACHINE SDKMACHINE DISTRO OEROOT
}

# get command line options
SHORTOPTS="h"
LONGOPTS="help"

ARGS=$(getopt --options $SHORTOPTS  \
  --longoptions $LONGOPTS --name $PROGNAME -- "$@" )
# Print the usage menu if invalid options are specified
if [ $? != 0 -o $# -lt 1 ]; then
   usage && clean_up
   return 1
fi

eval set -- "$ARGS"
while true;do
    case $1 in
        -h|--help)
           usage
           clean_up
           return 0
           ;;
        --)
           shift
           break
           ;;
    esac
done

if [ "$(whoami)" = "root" ]; then
    echo "ERROR: do not use yocto as root! Exiting..."
    return 1
fi

if [ ! -e "$1/conf/local.conf.sample" ]; then
    build_dir_setup_enabled=true
else
    build_dir_setup_enabled=false
fi

if $build_dir_setup_enabled && [ -z "$MACHINE" ];then
    usage
    echo -e "ERROR: You must set MACHINE when creating a new build directory."
    clean_up
    return 1
fi

# Check the machine type specified
LIST_MACHINES=`ls -1 $CWD/layers/*/conf/machine`
VALID_MACHINE=`echo -e "$LIST_MACHINES" | grep ${MACHINE}.conf$ | wc -l`
if [ "$MACHINE" = "" ] || [ "$VALID_MACHINE" = "0" ]; then
    echo -e "\nThe \$MACHINE you have specified ($MACHINE) is not supported by this build setup"
    usage && clean_up
    return 1
fi
if [ ! -e $TEMPLATECONF/local.conf.sample ]; then
    echo "Configuring for ${MACHINE}"
fi

if [ -z "$SDKMACHINE" ]; then
    SDKMACHINE=`uname -m`
fi

if [ -z "$DISTRO" ]; then
    DISTRO="karo-minimal"
fi
shopt -q nullglob && nullglob=false || nullglob=true
$nullglob && shopt -s nullglob
distro_dirs="`find layers -path "*/conf/distro/${DISTRO}.conf" -printf "%h\n"`"
if [ -z "$distro_dirs" ];then
    echo "Unsupported distro: '$DISTRO'" >&2
    usage && clean_up
    return 1
fi
bitbake_target=""
for d in $distro_dirs;do
    dir="`dirname "${d}"`/../recipes-core/images"
    [ -d "$dir" ] || continue
    distro_images="`cd "$dir" && ls *.bb`"
    bitbake_target="${bitbake_target} ${distro_images//.bb/ }"
done
for t in $bitbake_target;do
    if [ "${t/-image/}" = "${DISTRO}" ];then
        bitbake_target="$t"
        break
    elif [ "${DISTRO}" = "karo-wayland" ];then
        bitbake_target="karo-image-weston"
        break;
    fi
done

OEROOT=$PWD/layers/poky
if [ -e $PWD/layers/oe-core ]; then
    OEROOT=$PWD/layers/oe-core
fi

# Ensure all files in layers/base are kept in sync with project root
updated=false
for f in "$CWD/layers/meta-karo/base/"*; do
    file="$(basename $f)"
    if [ "$file" = "conf" ] || echo "$file" | grep -q '~$'; then
        continue
    fi

    if ! cmp -s "$file" "$f"; then
        updated=true
        [ -e "$file" ] && chmod u+w "$file"
        cp "$f" "$file"
    fi
done
$nullglob && shopt -u nullglob
if $updated; then
    echo "The project root content has been updated. Please run '$PROGNAME' again."
    return
fi

. $OEROOT/oe-init-build-env $CWD/$1 > /dev/null

# if conf/local.conf not generated, no need to go further
if [ ! -e conf/local.conf ]; then
    clean_up && return 1
fi

# Clean up PATH, because if it includes tokens to current directories somehow,
# wrong binaries can be used instead of the expected ones during task execution
export PATH="`echo $PATH | sed 's/\(:.\|:\)*:/:/g;s/^.\?://;s/:.\?$//'`"

generated_config=
if $build_dir_setup_enabled; then
    mv conf/local.conf conf/local.conf.sample

    # Generate the local.conf based on the Yocto defaults
    grep -v '^#\|^$' conf/local.conf.sample > conf/local.conf

    if [ "$DISTRO" = "karo-minimal" ];then
        echo 'EXTRA_IMAGE_FEATURES += "read-only-rootfs"' >> conf/local.conf
    fi
    # Change settings according environment
    sed -e "s,MACHINE ??=.*,MACHINE ??= '$MACHINE',g" \
        -e "s,SDKMACHINE ??=.*,SDKMACHINE ??= '$SDKMACHINE',g" \
        -e "s,DISTRO ?=.*,DISTRO ?= '$DISTRO',g" \
        -e "s,POKY_DISTRO ?=.*,POKY_DISTRO ?= '$POKY_DISTRO',g" \
        -i conf/local.conf

    cp $TEMPLATECONF/* conf/

    for s in $HOME/.oe $HOME/.yocto; do
        if [ -e $s/site.conf ]; then
            echo "Linking $s/site.conf to conf/site.conf"
            ln -s $s/site.conf conf
        fi
    done

    generated_config=1
fi

cat <<EOF

Welcome to Ka-Ro electronics TX and QS module BSP

The Yocto Project has extensive documentation about OE including a
reference manual which can be found at:
    https://yoctoproject.org/documentation

For more information about OpenEmbedded see their website:
    https://www.openembedded.org/

For Ka-Ro specific documentation please refer to:
    "Getting Started" > "Documentation" in the products page on
    https://www.karo-electronics.com

You can start your build now with:
$(for i in ${bitbake_target:-core-image-minimal};do \
    echo "    bitbake $i"; \
done )

EOF

if [ -n "$generated_config" ]; then
    cat <<EOF
Your build environment has been configured with:

    MACHINE=$MACHINE
    SDKMACHINE=$SDKMACHINE
    DISTRO=$DISTRO
EOF
else
    echo "Your configuration files at $1 have not been touched."
fi

clean_up
